### ISSUE TITLE
Error on first run (ascii_text_art.rb:15:in ``': No such file or directory -  (Errno::ENOENT))

### ISSUE THREAD

**Issue by eevahr** [taylorthurlow/panda-motd#12]
### Bug description
Get error on first run of panda-motd, not familiar with ruby, so i cant describe the bug better than this.
output of `cat /var/log/panda-motd.error.log`:

```
/var/lib/gems/2.3.0/gems/panda-motd-0.0.7/lib/panda_motd/components/ascii_text_art.rb:15:in ``': No such file or directory -  (Errno::ENOENT)
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.7/lib/panda_motd/components/ascii_text_art.rb:15:in `process'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.7/lib/panda_motd/motd.rb:9:in `each'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.7/lib/panda_motd/motd.rb:9:in `initialize'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.7/lib/panda_motd.rb:9:in `new'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.7/lib/panda_motd.rb:9:in `new_motd'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.7/bin/panda-motd:5:in `<top (required)>'
        from /usr/local/bin/panda-motd:23:in `load'
        from /usr/local/bin/panda-motd:23:in `<main>'
```

### Reproduction steps
1. Run panda-motd

### Expected behavior
I expected panda-motd to print a successful result.

### OS Information
 - OS: Ubuntu 16.04 LTS
 - rb v: 2.3.0

### Configuration File

https://gist.github.com/eevahr/ae2e87642f55c0a1704cc6a093aa1953

**Comment by taylorthurlow** [comment]
Hi. You're getting this error because in `0.0.7` a `command` setting was added to the ASCII art text config. [Here's the setting you're missing.](https://github.com/taylorthurlow/panda-motd/blob/develop/lib/panda_motd/default_config.yaml#L26)

**Comment by eevahr** [comment]
That's it, ooh yeah. thanks.
