### ISSUE TITLE
Automagically Sort SSL Certificates

### ISSUE THREAD

**Issue by RyoshiKayo** [taylorthurlow/panda-motd#14]
**Describe the solution you'd like**
When rendering/displaying the SSL Certificates, automagically sort them alphabetically by default, and also have the option to sort by expiration date, ex, having the certificates that are going to expire listed first.

**Describe alternatives you've considered**
Manually sorting certificates :(

**Comment by taylorthurlow** [comment]
Please ignore the merge spam haha, had a small issue with the first PR. I've added this feature, you should be able to find it on the `develop` branch, or in the next release of the gem. Thanks for the feedback!
