### ISSUE TITLE
Fail2Ban Component

### ISSUE THREAD

**Issue by taylorthurlow** [taylorthurlow/panda-motd#24]
Would be cool to have fail2ban statistics.

**Comment by taylorthurlow** [comment]
Nice article, looks like it's what we'd need. I'm not sure about `logresolve`, the article says it can be slow. Worth testing out, though. Perhaps some sort of name caching so you only have to do a domain lookup for an IP once.

If you wanna give this one ago feel free, I might be able to find some time soon-ish to give this a try if you don't want to.

**Comment by filalex77** [comment]
Probably not now, kind of busy :(
If I find some time soon, I'll let you know.
Feel free to start any time you want!
