### ISSUE TITLE
wrong uptime displayed

### ISSUE THREAD

**Issue by jeannot49** [taylorthurlow/panda-motd#30]
### Bug description
The uptime displayed by panda-motd isn't the good one.

### Reproduction steps
Uncomment the "uptime" paragraph in ~/.config/panda-motd

### Expected behavior
Have the right uptime displayed

### Screenshots
See the red ractangles
![issue](https://user-images.githubusercontent.com/39265653/52906808-8adea700-3254-11e9-80d7-afab7b4be35d.PNG)

### OS Information
 - OS: Debian 9.7 64 bits

### Configuration File
  uptime:
    enabled: true
    prefix: up

**Comment by taylorthurlow** [comment]
Okay this one might be harder to figure out. I use [sysinfo](https://github.com/delano/sysinfo) to grab system uptime. On unix-based systems, the gem should be executing the command `who -b` to determine the time the system booted. What's your output when you run `who -b`?

**Comment by jeannot49** [comment]
Hello,
I have that when I run who -b : 
démarrage système 2008-01-01 01:00

It's in french it means "system startup".

**Comment by taylorthurlow** [comment]
Well that's your problem. Not sure why it's saying you last booted in 2008, though. What is the result of the command `date`?

**Comment by jeannot49** [comment]
date displays the right date : 
Wednesday 27th February 2019, 20:27:31 (UTC+0100)

**Comment by taylorthurlow** [comment]
Gotcha. I'll close this for now, it seems like this is really an issue with however `who -b` gets it's information. Keep an eye on it and let me know if the issue comes back.

**Comment by jeannot49** [comment]
Got it, thanks!
